CREATE TABLE IF NOT EXISTS mr_trade_input (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    data_date DATE NOT NULL,
    trade_id VARCHAR(128) NOT NULL,
    product_type VARCHAR(64) NOT NULL,
    trade_content_text CLOB NOT NULL,
    content_format VARCHAR(16) NOT NULL DEFAULT 'JSON',
    version_no INT NOT NULL DEFAULT 1,
    source_system VARCHAR(128),
    created_at BIGINT NOT NULL,
    updated_at BIGINT NOT NULL,
    CONSTRAINT uk_mr_trade_input UNIQUE (data_date, trade_id, version_no)
);

CREATE INDEX IF NOT EXISTS idx_mr_trade_input_date
    ON mr_trade_input (data_date);

CREATE INDEX IF NOT EXISTS idx_mr_trade_input_product
    ON mr_trade_input (product_type);

CREATE TABLE IF NOT EXISTS mr_market_curve_input (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    data_date DATE NOT NULL,
    market_data_type VARCHAR(64) NOT NULL,
    curve_id VARCHAR(128) NOT NULL,
    curve_content_text CLOB NOT NULL,
    content_format VARCHAR(16) NOT NULL DEFAULT 'JSON',
    version_no INT NOT NULL DEFAULT 1,
    source_system VARCHAR(128),
    created_at BIGINT NOT NULL,
    updated_at BIGINT NOT NULL,
    CONSTRAINT uk_mr_market_curve_input UNIQUE (data_date, market_data_type, curve_id, version_no)
);

CREATE INDEX IF NOT EXISTS idx_mr_market_curve_input_date
    ON mr_market_curve_input (data_date);

CREATE INDEX IF NOT EXISTS idx_mr_market_curve_input_type
    ON mr_market_curve_input (market_data_type);

CREATE INDEX IF NOT EXISTS idx_mr_market_curve_input_curve
    ON mr_market_curve_input (curve_id);
