-- 批量任务主表
CREATE TABLE IF NOT EXISTS mr_async_batch_job (
    batch_id VARCHAR(64) PRIMARY KEY,
    request_id VARCHAR(128) NOT NULL,
    engine_code VARCHAR(64) NOT NULL,
    trace_id VARCHAR(128),
    client_id VARCHAR(128),
    user_id VARCHAR(128),
    user_name VARCHAR(128),
    source_system VARCHAR(128),
    op_code VARCHAR(64) NOT NULL,
    data_date DATE NOT NULL,
    portfolio VARCHAR(128),
    desk VARCHAR(64),
    total_trades INT NOT NULL,
    total_jobs INT NOT NULL,
    chunk_size INT NOT NULL,
    status VARCHAR(32) NOT NULL,
    pending_jobs INT NOT NULL DEFAULT 0,
    running_jobs INT NOT NULL DEFAULT 0,
    success_jobs INT NOT NULL DEFAULT 0,
    failed_jobs INT NOT NULL DEFAULT 0,
    cancelled_jobs INT NOT NULL DEFAULT 0,
    message VARCHAR(1024),
    created_at BIGINT NOT NULL,
    updated_at BIGINT NOT NULL
);

-- 批量任务子项表
CREATE TABLE IF NOT EXISTS mr_async_batch_item (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    batch_id VARCHAR(64) NOT NULL,
    seq_no INT NOT NULL,
    job_id VARCHAR(64) NOT NULL,
    trade_count INT NOT NULL,
    product_mix_json TEXT,
    created_at BIGINT NOT NULL
);

-- 索引
CREATE UNIQUE INDEX IF NOT EXISTS uk_mr_async_batch_item_seq
    ON mr_async_batch_item(batch_id, seq_no);
CREATE UNIQUE INDEX IF NOT EXISTS uk_mr_async_batch_item_job
    ON mr_async_batch_item(job_id);
CREATE INDEX IF NOT EXISTS idx_mr_async_batch_item_batch
    ON mr_async_batch_item(batch_id);
CREATE INDEX IF NOT EXISTS idx_mr_async_batch_job_status
    ON mr_async_batch_job(status);
