package com.zcyh.mr.springboot.service;

import com.zcyh.mr.springboot.context.RequestContext;
import com.zcyh.mr.springboot.context.RequestContextHolder;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.stereotype.Service;

/**
 * 审计日志服务。
 */
@Service
public class AuditLogService {
    private static final Logger log = LoggerFactory.getLogger(AuditLogService.class);

    private final JdbcTemplate jdbcTemplate;
    private final boolean enabled;

    public AuditLogService(
            JdbcTemplate jdbcTemplate,
            @Value("${mr.audit.enabled:true}") boolean enabled,
            @Value("${mr.job.store.jdbc.init-schema:true}") boolean initSchema
    ) {
        this.jdbcTemplate = jdbcTemplate;
        this.enabled = enabled;
        if (initSchema) {
            initSchema();
        }
    }

    public void recordSuccess(String action, String resourceType, String resourceId, String engineCode, String message, long elapsedMs) {
        record(action, resourceType, resourceId, engineCode, true, null, message, elapsedMs);
    }

    public void recordFailure(String action, String resourceType, String resourceId, String engineCode, String errorCode, String message, long elapsedMs) {
        record(action, resourceType, resourceId, engineCode, false, errorCode, message, elapsedMs);
    }

    private void record(String action, String resourceType, String resourceId, String engineCode, boolean success, String errorCode, String message, long elapsedMs) {
        if (!enabled) {
            return;
        }
        RequestContext context = RequestContextHolder.snapshot();
        long now = System.currentTimeMillis();
        try {
            jdbcTemplate.update(
                    "INSERT INTO mr_audit_log (trace_id, request_id, client_id, user_id, user_name, source_system, action, resource_type, resource_id, engine_code, success_flag, error_code, message, remote_ip, request_uri, http_method, elapsed_ms, created_at) "
                            + "VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)",
                    safe(context == null ? null : context.getTraceId()),
                    safe(context == null ? null : context.getRequestId()),
                    safe(context == null ? null : context.getClientId()),
                    safe(context == null ? null : context.getUserId()),
                    safe(context == null ? null : context.getUserName()),
                    safe(context == null ? null : context.getSourceSystem()),
                    safe(action),
                    safe(resourceType),
                    safe(resourceId),
                    safe(engineCode),
                    success ? 1 : 0,
                    safe(errorCode),
                    safe(message),
                    safe(context == null ? null : context.getRemoteIp()),
                    safe(context == null ? null : context.getRequestUri()),
                    safe(context == null ? null : context.getMethod()),
                    Math.max(0L, elapsedMs),
                    now
            );
        } catch (Exception ex) {
            log.error("审计日志写入失败，action={}, resourceType={}, resourceId={}", action, resourceType, resourceId, ex);
        }
    }

    private void initSchema() {
        try {
            jdbcTemplate.execute("CREATE TABLE IF NOT EXISTS mr_audit_log ("
                    + "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,"
                    + "trace_id VARCHAR(128),"
                    + "request_id VARCHAR(128),"
                    + "client_id VARCHAR(128),"
                    + "user_id VARCHAR(128),"
                    + "user_name VARCHAR(128),"
                    + "source_system VARCHAR(128),"
                    + "action VARCHAR(64) NOT NULL,"
                    + "resource_type VARCHAR(64),"
                    + "resource_id VARCHAR(128),"
                    + "engine_code VARCHAR(64),"
                    + "success_flag SMALLINT NOT NULL,"
                    + "error_code VARCHAR(64),"
                    + "message VARCHAR(2048),"
                    + "remote_ip VARCHAR(64),"
                    + "request_uri VARCHAR(512),"
                    + "http_method VARCHAR(16),"
                    + "elapsed_ms BIGINT,"
                    + "created_at BIGINT NOT NULL)");
            jdbcTemplate.execute("CREATE INDEX IF NOT EXISTS idx_mr_audit_log_created_at ON mr_audit_log(created_at)");
            jdbcTemplate.execute("CREATE INDEX IF NOT EXISTS idx_mr_audit_log_action ON mr_audit_log(action)");
        } catch (Exception ex) {
            log.warn("初始化审计日志表失败: {}", ex.getMessage());
        }
    }

    private static String safe(String txt) {
        if (txt == null) {
            return null;
        }
        String value = txt.trim();
        return value.isEmpty() ? null : value;
    }
}
