package com.zcyh.mr.springboot.api;

import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.zcyh.mr.springboot.MrSpringBootApplication;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.web.servlet.AutoConfigureMockMvc;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.http.MediaType;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.test.context.TestPropertySource;
import org.springframework.test.web.servlet.MockMvc;
import org.springframework.test.web.servlet.MvcResult;

import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.get;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.post;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.status;

/**
 * 批量异步接口自动化测试。
 */
@SpringBootTest(classes = MrSpringBootApplication.class)
@AutoConfigureMockMvc
@TestPropertySource(properties = {
        "spring.datasource.url=jdbc:h2:mem:mrbatchtest;MODE=MySQL;DB_CLOSE_DELAY=-1",
        "spring.datasource.username=sa",
        "spring.datasource.password=",
        "spring.datasource.driver-class-name=org.h2.Driver",
        "mr.job.store.jdbc.init-schema=true",
        "mr.job.store.node-id=test-node",
        "mr.job.executor.core-size=1",
        "mr.job.executor.max-size=2",
        "mr.job.executor.queue-capacity=100",
        "mr.job.store.cleanup.every-submit=1",
        "mr.job.store.cleanup.retention-days=30",
        "mr.job.client.poll-after-ms=120",
        "mr.batch.chunk-size=100",
        "mr.batch.weight-default=5",
        "mr.batch.client.poll-after-ms=120"
})
public class MrBatchJobControllerTest {

    @Autowired
    private MockMvc mockMvc;

    @Autowired
    private ObjectMapper objectMapper;

    @Autowired
    private JdbcTemplate jdbcTemplate;

    @BeforeEach
    void setupData() {
        jdbcTemplate.execute("CREATE TABLE IF NOT EXISTS mr_trade_input ("
                + "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,"
                + "data_date DATE NOT NULL,"
                + "trade_id VARCHAR(128) NOT NULL,"
                + "product_type VARCHAR(64) NOT NULL,"
                + "trade_content_text CLOB NOT NULL,"
                + "content_format VARCHAR(16) NOT NULL DEFAULT 'JSON',"
                + "version_no INT NOT NULL DEFAULT 1,"
                + "source_system VARCHAR(128),"
                + "created_at BIGINT NOT NULL,"
                + "updated_at BIGINT NOT NULL,"
                + "trader VARCHAR(64),"
                + "portfolio VARCHAR(128),"
                + "desk VARCHAR(64)"
                + ")");
        jdbcTemplate.execute("CREATE TABLE IF NOT EXISTS mr_market_curve_input ("
                + "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,"
                + "data_date DATE NOT NULL,"
                + "market_data_type VARCHAR(64) NOT NULL,"
                + "curve_id VARCHAR(128) NOT NULL,"
                + "curve_content_text CLOB NOT NULL,"
                + "content_format VARCHAR(16) NOT NULL DEFAULT 'JSON',"
                + "version_no INT NOT NULL DEFAULT 1,"
                + "source_system VARCHAR(128),"
                + "created_at BIGINT NOT NULL,"
                + "updated_at BIGINT NOT NULL"
                + ")");
        jdbcTemplate.execute("CREATE TABLE IF NOT EXISTS mr_async_batch_job ("
                + "batch_id VARCHAR(64) PRIMARY KEY,"
                + "request_id VARCHAR(128) NOT NULL,"
                + "engine_code VARCHAR(64) NOT NULL,"
                + "op_code VARCHAR(64) NOT NULL,"
                + "data_date DATE NOT NULL,"
                + "portfolio VARCHAR(128),"
                + "desk VARCHAR(64),"
                + "total_trades INT NOT NULL,"
                + "total_jobs INT NOT NULL,"
                + "chunk_size INT NOT NULL,"
                + "status VARCHAR(32) NOT NULL,"
                + "pending_jobs INT NOT NULL DEFAULT 0,"
                + "running_jobs INT NOT NULL DEFAULT 0,"
                + "success_jobs INT NOT NULL DEFAULT 0,"
                + "failed_jobs INT NOT NULL DEFAULT 0,"
                + "cancelled_jobs INT NOT NULL DEFAULT 0,"
                + "message VARCHAR(1024),"
                + "created_at BIGINT NOT NULL,"
                + "updated_at BIGINT NOT NULL"
                + ")");
        jdbcTemplate.execute("CREATE TABLE IF NOT EXISTS mr_async_batch_item ("
                + "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,"
                + "batch_id VARCHAR(64) NOT NULL,"
                + "seq_no INT NOT NULL,"
                + "job_id VARCHAR(64) NOT NULL,"
                + "trade_count INT NOT NULL,"
                + "product_mix_json CLOB,"
                + "created_at BIGINT NOT NULL"
                + ")");
        jdbcTemplate.execute("CREATE UNIQUE INDEX IF NOT EXISTS uk_mr_async_batch_item_seq ON mr_async_batch_item(batch_id, seq_no)");
        jdbcTemplate.execute("CREATE UNIQUE INDEX IF NOT EXISTS uk_mr_async_batch_item_job ON mr_async_batch_item(job_id)");
        jdbcTemplate.execute("CREATE INDEX IF NOT EXISTS idx_mr_async_batch_item_batch ON mr_async_batch_item(batch_id)");
        jdbcTemplate.execute("CREATE INDEX IF NOT EXISTS idx_mr_async_batch_job_status ON mr_async_batch_job(status)");
        jdbcTemplate.execute("DELETE FROM mr_trade_input");
        jdbcTemplate.execute("DELETE FROM mr_market_curve_input");
        jdbcTemplate.execute("DELETE FROM mr_async_batch_item");
        jdbcTemplate.execute("DELETE FROM mr_async_batch_job");

        long now = System.currentTimeMillis();
        String dataDate = "2026-02-25";
        String[] productTypes = new String[]{"FXFWD", "IRSCCS", "SWAPTION", "FXOPTION"};
        String[] desks = new String[]{"FX_DESK", "RATES_DESK", "EQ_DESK", "COMM_DESK"};
        String[] portfolios = new String[]{
                "PF_FX_01", "PF_FX_02", "PF_FX_03", "PF_FX_04",
                "PF_RT_01", "PF_RT_02", "PF_RT_03", "PF_RT_04",
                "PF_EQ_01", "PF_EQ_02", "PF_EQ_03", "PF_EQ_04",
                "PF_CM_01", "PF_CM_02", "PF_CM_03"
        };

        for (int i = 1; i <= 220; i++) {
            String tradeId = String.format("IT_TRADE_%04d", i);
            String productType = productTypes[(i - 1) % productTypes.length];
            String desk = desks[(i - 1) % desks.length];
            String portfolio = resolvePortfolio(portfolios, desk, i);
            String trader = String.format("TRADER_%02d", ((i - 1) % 10) + 1);
            String tradeJson = "{"
                    + "\"INSTRUMENT_ID\":\"" + tradeId + "\","
                    + "\"PRODUCT_CODE\":\"" + productType + "\","
                    + "\"BOOK\":\"" + portfolio + "\""
                    + "}";
            jdbcTemplate.update(
                    "INSERT INTO mr_trade_input (data_date, trade_id, product_type, trade_content_text, content_format, version_no, source_system, created_at, updated_at, trader, portfolio, desk) "
                            + "VALUES (?, ?, ?, ?, 'JSON', 1, 'it', ?, ?, ?, ?, ?)",
                    java.sql.Date.valueOf(dataDate),
                    tradeId,
                    productType,
                    tradeJson,
                    now,
                    now,
                    trader,
                    portfolio,
                    desk
            );
        }

        insertCurve(dataDate, "IR_CURVE", "CNY_IR", "{\"CURVE_ID\":\"CNY_IR\",\"POINTS\":[{\"t\":\"1Y\",\"v\":0.02}]}", now);
        insertCurve(dataDate, "FX_SPOT", "USDCNY", "{\"CURVE_ID\":\"USDCNY\",\"SPOT\":7.2}", now);
        insertCurve(dataDate, "FX_VOL", "USDCNY_VOL", "{\"CURVE_ID\":\"USDCNY_VOL\",\"ATM\":0.11}", now);
    }

    @Test
    void submitBatchAndGetDetail_shouldWork() throws Exception {
        String payload = "{"
                + "\"requestId\":\"it-batch-001\","
                + "\"engineCode\":\"mr_calc\","
                + "\"opCode\":\"PRICING\","
                + "\"dataDate\":\"2026-02-25\""
                + "}";

        MvcResult submitRes = mockMvc.perform(post("/api/v1/jobs/batch/submit")
                        .contentType(MediaType.APPLICATION_JSON)
                        .content(payload))
                .andExpect(status().isOk())
                .andReturn();
        JsonNode submitJson = objectMapper.readTree(submitRes.getResponse().getContentAsString());
        String batchId = submitJson.at("/data/batchId").asText();
        Assertions.assertFalse(batchId.isEmpty(), "batchId 不能为空");
        Assertions.assertEquals(220, submitJson.at("/data/totalTrades").asInt(), "交易总数应匹配");
        Assertions.assertEquals(3, submitJson.at("/data/totalJobs").asInt(), "应按 100 自动分片");
        Assertions.assertEquals(100, submitJson.at("/data/chunkSize").asInt(), "分片大小应匹配配置");

        JsonNode detailJson = waitUntilDone(batchId, 40, 150L);
        Assertions.assertTrue(detailJson.at("/success").asBoolean(), "接口响应应成功");
        Assertions.assertEquals(3, detailJson.at("/data/totalJobs").asInt(), "批次任务数应匹配");
        int pending = detailJson.at("/data/pendingJobs").asInt();
        int running = detailJson.at("/data/runningJobs").asInt();
        int success = detailJson.at("/data/successJobs").asInt();
        int failed = detailJson.at("/data/failedJobs").asInt();
        int cancelled = detailJson.at("/data/cancelledJobs").asInt();
        Assertions.assertEquals(3, pending + running + success + failed + cancelled, "状态总数应等于总任务数");
        Assertions.assertEquals(3, detailJson.at("/data/jobs").size(), "应返回全部子任务");
    }

    @Test
    void submitBatchWithDeskFilter_shouldRestrictTrades() throws Exception {
        String payload = "{"
                + "\"requestId\":\"it-batch-002\","
                + "\"engineCode\":\"mr_calc\","
                + "\"opCode\":\"PRICING\","
                + "\"dataDate\":\"2026-02-25\","
                + "\"desk\":\"FX_DESK\""
                + "}";

        MvcResult submitRes = mockMvc.perform(post("/api/v1/jobs/batch/submit")
                        .contentType(MediaType.APPLICATION_JSON)
                        .content(payload))
                .andExpect(status().isOk())
                .andReturn();
        JsonNode submitJson = objectMapper.readTree(submitRes.getResponse().getContentAsString());
        Assertions.assertEquals(55, submitJson.at("/data/totalTrades").asInt(), "按 desk 过滤后交易数应匹配");
        Assertions.assertEquals(1, submitJson.at("/data/totalJobs").asInt(), "过滤后应只生成一个子任务");
    }

    private void insertCurve(String dataDate, String marketType, String curveId, String content, long now) {
        jdbcTemplate.update(
                "INSERT INTO mr_market_curve_input (data_date, market_data_type, curve_id, curve_content_text, content_format, version_no, source_system, created_at, updated_at) "
                        + "VALUES (?, ?, ?, ?, 'JSON', 1, 'it', ?, ?)",
                java.sql.Date.valueOf(dataDate),
                marketType,
                curveId,
                content,
                now,
                now
        );
    }

    private String resolvePortfolio(String[] portfolios, String desk, int idx) {
        if ("FX_DESK".equals(desk)) {
            return portfolios[(idx - 1) % 4];
        }
        if ("RATES_DESK".equals(desk)) {
            return portfolios[4 + ((idx - 1) % 4)];
        }
        if ("EQ_DESK".equals(desk)) {
            return portfolios[8 + ((idx - 1) % 4)];
        }
        return portfolios[12 + ((idx - 1) % 3)];
    }

    /**
     * 轮询批次状态直到完成或达到最大轮询次数。
     */
    private JsonNode waitUntilDone(String batchId, int maxRounds, long sleepMillis) throws Exception {
        JsonNode latest = null;
        for (int i = 0; i < maxRounds; i++) {
            MvcResult detailRes = mockMvc.perform(get("/api/v1/jobs/batch/{batchId}", batchId))
                    .andExpect(status().isOk())
                    .andReturn();
            latest = objectMapper.readTree(detailRes.getResponse().getContentAsString());
            if (latest.at("/data/done").asBoolean()) {
                return latest;
            }
            Thread.sleep(sleepMillis);
        }
        return latest;
    }
}
