-- =========================================================
-- MySQL 迁移后行数校验 SQL
-- =========================================================

USE mr_engine;

SELECT 'MR_TRADE_INPUT' AS table_name, COUNT(*) AS cnt FROM MR_TRADE_INPUT
UNION ALL SELECT 'MR_MARKET_CURVE_INPUT', COUNT(*) FROM MR_MARKET_CURVE_INPUT
UNION ALL SELECT 'MR_RISKFACTOR_DATA', COUNT(*) FROM MR_RISKFACTOR_DATA
UNION ALL SELECT 'MR_SCENARIO_RULE', COUNT(*) FROM MR_SCENARIO_RULE
UNION ALL SELECT 'MR_AGG_RULE', COUNT(*) FROM MR_AGG_RULE
UNION ALL SELECT 'MR_ASYNC_JOB', COUNT(*) FROM MR_ASYNC_JOB
UNION ALL SELECT 'MR_ASYNC_BATCH_JOB', COUNT(*) FROM MR_ASYNC_BATCH_JOB
UNION ALL SELECT 'MR_ASYNC_BATCH_ITEM', COUNT(*) FROM MR_ASYNC_BATCH_ITEM
UNION ALL SELECT 'MR_AUDIT_LOG', COUNT(*) FROM MR_AUDIT_LOG;



