CREATE TABLE IF NOT EXISTS mr_audit_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    trace_id VARCHAR(128),
    request_id VARCHAR(128),
    client_id VARCHAR(128),
    user_id VARCHAR(128),
    user_name VARCHAR(128),
    source_system VARCHAR(128),
    action VARCHAR(64) NOT NULL,
    resource_type VARCHAR(64),
    resource_id VARCHAR(128),
    engine_code VARCHAR(64),
    success_flag SMALLINT NOT NULL,
    error_code VARCHAR(64),
    message VARCHAR(2048),
    remote_ip VARCHAR(64),
    request_uri VARCHAR(512),
    http_method VARCHAR(16),
    elapsed_ms BIGINT,
    created_at BIGINT NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_mr_audit_log_created_at ON mr_audit_log(created_at);
CREATE INDEX IF NOT EXISTS idx_mr_audit_log_action ON mr_audit_log(action);
