CREATE TABLE IF NOT EXISTS MR_TRADE_INPUT (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    data_date DATE NOT NULL,
    trade_id VARCHAR(128) NOT NULL,
    product_type VARCHAR(64) NOT NULL,
    trade_content_text CLOB NOT NULL,
    content_format VARCHAR(16) NOT NULL DEFAULT 'JSON',
    version_no INT NOT NULL DEFAULT 1,
    source_system VARCHAR(128),
    portfolio VARCHAR(128),
    desk VARCHAR(64),
    trader VARCHAR(64),
    created_at BIGINT NOT NULL,
    updated_at BIGINT NOT NULL,
    CONSTRAINT uk_MR_TRADE_INPUT UNIQUE (data_date, trade_id, version_no)
);

CREATE INDEX IF NOT EXISTS idx_MR_TRADE_INPUT_date
    ON MR_TRADE_INPUT (data_date);

CREATE INDEX IF NOT EXISTS idx_MR_TRADE_INPUT_product
    ON MR_TRADE_INPUT (product_type);

CREATE TABLE IF NOT EXISTS MR_MARKET_CURVE_INPUT (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    data_date DATE NOT NULL,
    market_data_type VARCHAR(64) NOT NULL,
    curve_id VARCHAR(128) NOT NULL,
    curve_content_text CLOB NOT NULL,
    content_format VARCHAR(16) NOT NULL DEFAULT 'JSON',
    version_no INT NOT NULL DEFAULT 1,
    source_system VARCHAR(128),
    created_at BIGINT NOT NULL,
    updated_at BIGINT NOT NULL,
    CONSTRAINT uk_MR_MARKET_CURVE_INPUT UNIQUE (data_date, market_data_type, curve_id, version_no)
);

CREATE INDEX IF NOT EXISTS idx_MR_MARKET_CURVE_INPUT_date
    ON MR_MARKET_CURVE_INPUT (data_date);

CREATE INDEX IF NOT EXISTS idx_MR_MARKET_CURVE_INPUT_type
    ON MR_MARKET_CURVE_INPUT (market_data_type);

CREATE INDEX IF NOT EXISTS idx_MR_MARKET_CURVE_INPUT_curve
    ON MR_MARKET_CURVE_INPUT (curve_id);

CREATE TABLE IF NOT EXISTS MR_RISKFACTOR_DATA (
    data_date DATE NOT NULL,
    riskfactor_type VARCHAR(64) NOT NULL,
    riskfactor_id VARCHAR(128) NOT NULL,
    term_code VARCHAR(64),
    term_days INT,
    obs_date DATE NOT NULL,
    riskfactor_value DECIMAL(30, 12) NOT NULL,
    currency VARCHAR(32),
    source_system VARCHAR(128),
    version_no INT NOT NULL DEFAULT 1,
    modifier VARCHAR(128),
    updated_at BIGINT NOT NULL,
    CONSTRAINT pk_MR_RISKFACTOR_DATA PRIMARY KEY (
        data_date, riskfactor_type, riskfactor_id, obs_date, term_code
    )
);

CREATE INDEX IF NOT EXISTS idx_MR_RISKFACTOR_DATA_main
    ON MR_RISKFACTOR_DATA (data_date, riskfactor_type, riskfactor_id);

CREATE TABLE IF NOT EXISTS MR_SCENARIO_RULE (
    scenario_id VARCHAR(128) NOT NULL,
    line_no INT NOT NULL,
    scenario_name VARCHAR(256) NOT NULL,
    scenario_type VARCHAR(32) NOT NULL,
    curve_type VARCHAR(64),
    curve_code VARCHAR(128),
    term_code VARCHAR(64),
    term_days INT,
    scenario_no INT,
    increase_days INT,
    junp_day_no INT,
    shock_type VARCHAR(32),
    cal_start_date DATE,
    cal_end_date DATE,
    start_date DATE,
    holiday_calendar VARCHAR(64),
    scenario_shift_value DECIMAL(30, 12),
    scenario_shift_rule VARCHAR(32),
    status VARCHAR(16) NOT NULL DEFAULT 'ACTIVE',
    remark VARCHAR(512),
    modifier VARCHAR(128),
    created_at BIGINT NOT NULL,
    updated_at BIGINT NOT NULL,
    CONSTRAINT pk_MR_SCENARIO_RULE PRIMARY KEY (scenario_id, line_no)
);

CREATE INDEX IF NOT EXISTS idx_MR_SCENARIO_RULE_type
    ON MR_SCENARIO_RULE (scenario_type, status);

CREATE INDEX IF NOT EXISTS idx_MR_SCENARIO_RULE_curve
    ON MR_SCENARIO_RULE (scenario_id, curve_type, curve_code);

CREATE TABLE IF NOT EXISTS MR_AGG_RULE (
    rule_id VARCHAR(128) PRIMARY KEY,
    rule_type VARCHAR(64) NOT NULL,
    rule_name VARCHAR(256),
    rule_json CLOB NOT NULL,
    modifier VARCHAR(128),
    created_at BIGINT NOT NULL,
    updated_at BIGINT NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_MR_AGG_RULE_type
    ON MR_AGG_RULE (rule_type);

MERGE INTO MR_AGG_RULE t
USING (
    SELECT
        'BATCH_FRTB_DEFAULT' AS rule_id,
        'FRTB' AS rule_type,
        '默认 FRTB 批次汇总规则' AS rule_name,
        '{
  "buildOrder": ["TRADER", "DESK", "PORTFOLIO", "TOTAL"],
  "dimensions": {
    "TRADER": "TRADER",
    "DESK": "DESK",
    "PORTFOLIO": "PORTFOLIO"
  },
  "groupByFields": ["PORTFOLIO", "DESK", "TRADER"],
  "sumFields": ["SENSITIVITY_VAL_INST_CURR_CNY"],
  "filters": []
}' AS rule_json,
        'system' AS modifier,
        0 AS created_at,
        0 AS updated_at
) s
ON (t.rule_id = s.rule_id)
WHEN MATCHED THEN UPDATE SET
    t.rule_type = s.rule_type,
    t.rule_name = s.rule_name,
    t.rule_json = s.rule_json,
    t.modifier = s.modifier,
    t.updated_at = s.updated_at
WHEN NOT MATCHED THEN INSERT (
    rule_id, rule_type, rule_name, rule_json, modifier, created_at, updated_at
) VALUES (
    s.rule_id, s.rule_type, s.rule_name, s.rule_json, s.modifier, s.created_at, s.updated_at
);


