-- BA-CVA输入表迁移
CREATE TABLE IF NOT EXISTS CVA_COUNTERPARTY (
    DATA_DATE        DATE         NOT NULL,
    COUNTERPARTY_ID  VARCHAR(128) NOT NULL,
    INDUSTRY         VARCHAR(32)  NOT NULL,
    CREDIT_QUALITY   VARCHAR(16)  NOT NULL,
    CREATED_AT       TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT       TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (DATA_DATE, COUNTERPARTY_ID)
) COMMENT='BA-CVA交易对手行业和信用水平';

CREATE TABLE IF NOT EXISTS CVA_NETTING_SET (
    DATA_DATE                DATE         NOT NULL,
    NETTING_SET_ID           VARCHAR(128) NOT NULL,
    COUNTERPARTY_ID          VARCHAR(128) NOT NULL,
    EFFECTIVE_MATURITY_YEARS DECIMAL(38,10) NOT NULL,
    CVA_SCOPE_FLAG           VARCHAR(16)  NOT NULL,
    CREATED_AT               TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT               TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (DATA_DATE, NETTING_SET_ID)
) COMMENT='BA-CVA净额集合范围和有效期限';

CREATE TABLE IF NOT EXISTS CVA_HEDGE (
    DATA_DATE                 DATE         NOT NULL,
    HEDGE_ID                  VARCHAR(128) NOT NULL,
    HEDGE_TYPE                VARCHAR(32)  NOT NULL,
    COUNTERPARTY_ID           VARCHAR(128),
    RELATION_TYPE             VARCHAR(32),
    REFERENCE_INDUSTRY        VARCHAR(32),
    REFERENCE_CREDIT_QUALITY  VARCHAR(16),
    INDEX_BASE_RISK_WEIGHT    DECIMAL(18,10),
    INDEX_DIVERSIFIED_FLAG    VARCHAR(1),
    REMAINING_MATURITY_YEARS  DECIMAL(38,10) NOT NULL,
    NOTIONAL_CNY              DECIMAL(38,10) NOT NULL,
    CREATED_AT                TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT                TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (DATA_DATE, HEDGE_ID)
) COMMENT='BA-CVA合格对冲交易';
