CREATE TABLE IF NOT EXISTS MR_TRADE_INPUT (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    data_date DATE NOT NULL,
    trade_id VARCHAR(128) NOT NULL,
    product_type VARCHAR(64) NOT NULL,
    trade_content_text CLOB NOT NULL,
    content_format VARCHAR(16) NOT NULL DEFAULT 'JSON',
    version_no INT NOT NULL DEFAULT 1,
    source_system VARCHAR(128),
    portfolio VARCHAR(128),
    desk VARCHAR(64),
    trader VARCHAR(64),
    created_at BIGINT NOT NULL,
    updated_at BIGINT NOT NULL,
    CONSTRAINT uk_MR_TRADE_INPUT UNIQUE (data_date, trade_id, version_no)
);

CREATE INDEX IF NOT EXISTS idx_MR_TRADE_INPUT_date
    ON MR_TRADE_INPUT (data_date);

CREATE INDEX IF NOT EXISTS idx_MR_TRADE_INPUT_product
    ON MR_TRADE_INPUT (product_type);

CREATE TABLE IF NOT EXISTS MR_MARKET_CURVE_INPUT (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    data_date DATE NOT NULL,
    market_data_type VARCHAR(64) NOT NULL,
    curve_id VARCHAR(128) NOT NULL,
    curve_content_text CLOB NOT NULL,
    content_format VARCHAR(16) NOT NULL DEFAULT 'JSON',
    version_no INT NOT NULL DEFAULT 1,
    source_system VARCHAR(128),
    created_at BIGINT NOT NULL,
    updated_at BIGINT NOT NULL,
    CONSTRAINT uk_MR_MARKET_CURVE_INPUT UNIQUE (data_date, market_data_type, curve_id, version_no)
);

CREATE INDEX IF NOT EXISTS idx_MR_MARKET_CURVE_INPUT_date
    ON MR_MARKET_CURVE_INPUT (data_date);

CREATE INDEX IF NOT EXISTS idx_MR_MARKET_CURVE_INPUT_type
    ON MR_MARKET_CURVE_INPUT (market_data_type);

CREATE INDEX IF NOT EXISTS idx_MR_MARKET_CURVE_INPUT_curve
    ON MR_MARKET_CURVE_INPUT (curve_id);

CREATE TABLE IF NOT EXISTS MR_RISKFACTOR_DATA (
    data_date DATE NOT NULL,
    riskfactor_type VARCHAR(64) NOT NULL,
    riskfactor_id VARCHAR(128) NOT NULL,
    term_code VARCHAR(64),
    term_days INT,
    obs_date DATE NOT NULL,
    riskfactor_value DECIMAL(30, 12) NOT NULL,
    currency VARCHAR(32),
    source_system VARCHAR(128),
    version_no INT NOT NULL DEFAULT 1,
    modifier VARCHAR(128),
    updated_at BIGINT NOT NULL,
    CONSTRAINT pk_MR_RISKFACTOR_DATA PRIMARY KEY (
        data_date, riskfactor_type, riskfactor_id, obs_date, term_code
    )
);

CREATE INDEX IF NOT EXISTS idx_MR_RISKFACTOR_DATA_main
    ON MR_RISKFACTOR_DATA (data_date, riskfactor_type, riskfactor_id);

CREATE TABLE IF NOT EXISTS MR_SCENARIO_RULE (
    scenario_id VARCHAR(128) NOT NULL,
    line_no INT NOT NULL,
    scenario_name VARCHAR(256) NOT NULL,
    scenario_type VARCHAR(32) NOT NULL,
    curve_type VARCHAR(64),
    curve_code VARCHAR(128),
    term_code VARCHAR(64),
    term_days INT,
    scenario_no INT,
    increase_days INT,
    junp_day_no INT,
    cal_start_date DATE,
    cal_end_date DATE,
    start_date DATE,
    holiday_calendar VARCHAR(64),
    scenario_shift_value DECIMAL(30, 12),
    scenario_shift_rule VARCHAR(32),
    status VARCHAR(16) NOT NULL DEFAULT 'ACTIVE',
    remark VARCHAR(512),
    modifier VARCHAR(128),
    created_at BIGINT NOT NULL,
    updated_at BIGINT NOT NULL,
    CONSTRAINT pk_MR_SCENARIO_RULE PRIMARY KEY (scenario_id, line_no)
);

CREATE INDEX IF NOT EXISTS idx_MR_SCENARIO_RULE_type
    ON MR_SCENARIO_RULE (scenario_type, status);

CREATE INDEX IF NOT EXISTS idx_MR_SCENARIO_RULE_curve
    ON MR_SCENARIO_RULE (scenario_id, curve_type, curve_code);

CREATE TABLE IF NOT EXISTS TB_17_CALENDAR (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    CALENDAR VARCHAR(64) NOT NULL,
    HOL_DATE DATE NOT NULL,
    PARENTID VARCHAR(128),
    APPROVER VARCHAR(128),
    MODIFIER VARCHAR(128),
    UPDATE_TIME TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_TB_17_CALENDAR_main
    ON TB_17_CALENDAR (CALENDAR, HOL_DATE);

DROP VIEW IF EXISTS V_SCENARIO_RULE;
CREATE VIEW V_SCENARIO_RULE AS
SELECT
    scenario_id,
    scenario_name,
    scenario_type,
    curve_type,
    curve_code,
    term_code,
    term_days,
    scenario_no,
    increase_days,
    junp_day_no,
    scenario_shift_value,
    scenario_shift_rule,
    start_date,
    holiday_calendar,
    CAST(NULL AS VARCHAR(128)) AS riskgroup_id
FROM MR_SCENARIO_RULE
WHERE status = 'ACTIVE';

DROP VIEW IF EXISTS V_CALENDAR;
CREATE VIEW V_CALENDAR AS
SELECT DISTINCT
    CALENDAR AS CALENDAR_CODE,
    HOL_DATE AS HOLIDAY_DATE
FROM TB_17_CALENDAR
WHERE CALENDAR IS NOT NULL
  AND HOL_DATE IS NOT NULL;

DROP VIEW IF EXISTS V_SCN_MKT_IR_SPOT;
CREATE VIEW V_SCN_MKT_IR_SPOT AS
SELECT
    'IR_SPOT' AS curve_type,
    riskfactor_id AS curve_code,
    data_date,
    COALESCE(term_code, CAST(term_days AS VARCHAR)) AS term_code,
    COALESCE(term_days, 0) AS term_days,
    riskfactor_value
FROM MR_RISKFACTOR_DATA
WHERE riskfactor_type = 'IR_SPOT';

DROP VIEW IF EXISTS V_SCN_MKT_FX_SPOT;
CREATE VIEW V_SCN_MKT_FX_SPOT AS
SELECT
    'FX_SPOT' AS curve_type,
    riskfactor_id AS curve_code,
    data_date,
    '0' AS term_code,
    0 AS term_days,
    riskfactor_value
FROM MR_RISKFACTOR_DATA
WHERE riskfactor_type = 'FX_SPOT';

DROP VIEW IF EXISTS V_SCN_MKT_COMM_SPOT;
CREATE VIEW V_SCN_MKT_COMM_SPOT AS
SELECT
    'COMM_SPOT' AS curve_type,
    riskfactor_id AS curve_code,
    data_date,
    COALESCE(term_code, CAST(term_days AS VARCHAR)) AS term_code,
    COALESCE(term_days, 0) AS term_days,
    riskfactor_value
FROM MR_RISKFACTOR_DATA
WHERE riskfactor_type = 'COMM_SPOT';

DROP VIEW IF EXISTS V_SCN_MKT_EQ_SPOT;
CREATE VIEW V_SCN_MKT_EQ_SPOT AS
SELECT
    'EQ_SPOT' AS curve_type,
    riskfactor_id AS curve_code,
    data_date,
    COALESCE(term_code, CAST(term_days AS VARCHAR)) AS term_code,
    COALESCE(term_days, 0) AS term_days,
    riskfactor_value
FROM MR_RISKFACTOR_DATA
WHERE riskfactor_type = 'EQ_SPOT';

DROP VIEW IF EXISTS V_SCN_MKT_FX_VOL;
CREATE VIEW V_SCN_MKT_FX_VOL AS
SELECT
    'FX_VOL' AS curve_type,
    riskfactor_id AS curve_code,
    data_date,
    COALESCE(term_code, CAST(term_days AS VARCHAR)) AS term_code,
    COALESCE(term_days, 0) AS term_days,
    COALESCE(term_code, CAST(term_days AS VARCHAR)) AS vertex2,
    riskfactor_value
FROM MR_RISKFACTOR_DATA
WHERE riskfactor_type = 'FX_VOL';

DROP VIEW IF EXISTS V_SCN_MKT_IR_VOL;
CREATE VIEW V_SCN_MKT_IR_VOL AS
SELECT
    'IR_VOL' AS curve_type,
    riskfactor_id AS curve_code,
    data_date,
    COALESCE(term_code, CAST(term_days AS VARCHAR)) AS term_code,
    COALESCE(term_days, 0) AS term_days,
    COALESCE(term_code, CAST(term_days AS VARCHAR)) AS vertex2,
    riskfactor_value
FROM MR_RISKFACTOR_DATA
WHERE riskfactor_type = 'IR_VOL';

DROP VIEW IF EXISTS V_SCN_MKT_COMM_VOL;
CREATE VIEW V_SCN_MKT_COMM_VOL AS
SELECT
    'COMM_VOL' AS curve_type,
    riskfactor_id AS curve_code,
    data_date,
    COALESCE(term_code, CAST(term_days AS VARCHAR)) AS term_code,
    COALESCE(term_days, 0) AS term_days,
    COALESCE(term_code, CAST(term_days AS VARCHAR)) AS vertex2,
    riskfactor_value
FROM MR_RISKFACTOR_DATA
WHERE riskfactor_type = 'COMM_VOL';

DROP VIEW IF EXISTS V_SCN_MKT_EQ_VOL;
CREATE VIEW V_SCN_MKT_EQ_VOL AS
SELECT
    'EQ_VOL' AS curve_type,
    riskfactor_id AS curve_code,
    data_date,
    COALESCE(term_code, CAST(term_days AS VARCHAR)) AS term_code,
    COALESCE(term_days, 0) AS term_days,
    COALESCE(term_code, CAST(term_days AS VARCHAR)) AS vertex2,
    riskfactor_value
FROM MR_RISKFACTOR_DATA
WHERE riskfactor_type = 'EQ_VOL';

CREATE TABLE IF NOT EXISTS MR_AGG_RULE (
    rule_id VARCHAR(128) PRIMARY KEY,
    rule_type VARCHAR(64) NOT NULL,
    rule_name VARCHAR(256),
    rule_json CLOB NOT NULL,
    modifier VARCHAR(128),
    created_at BIGINT NOT NULL,
    updated_at BIGINT NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_MR_AGG_RULE_type
    ON MR_AGG_RULE (rule_type);

INSERT INTO MR_AGG_RULE (
    rule_id, rule_type, rule_name, rule_json, modifier, created_at, updated_at
) VALUES (
    'BATCH_FRTB_DEFAULT',
    'FRTB',
    '默认 FRTB 批次汇总规则',
    '{"buildOrder":["TRADER","DESK","PORTFOLIO","TOTAL"],"dimensions":{"TRADER":"TRADER","DESK":"DESK","PORTFOLIO":"PORTFOLIO"},"groupByFields":["PORTFOLIO","DESK","TRADER"],"sumFields":["SENSITIVITY_VAL_INST_CURR_CNY"],"filters":[]}',
    'system',
    0,
    0
)
ON DUPLICATE KEY UPDATE
    rule_type = VALUES(rule_type),
    rule_name = VALUES(rule_name),
    rule_json = VALUES(rule_json),
    modifier = VALUES(modifier),
    updated_at = VALUES(updated_at);


