-- SA-CCR 输入表日期字段迁移。执行前必须确保 DATA_DATE 均为 yyyyMMdd 且非空。
ALTER TABLE SACCR_TRADE_CP MODIFY COLUMN DATA_DATE DATE NOT NULL COMMENT '数据日期';
ALTER TABLE SACCR_NETTING_SET MODIFY COLUMN DATA_DATE DATE NOT NULL COMMENT '数据日期';
ALTER TABLE SACCR_COLLATERAL_DETAIL MODIFY COLUMN DATA_DATE DATE NOT NULL COMMENT '数据日期';