-- 汇总规则字段统一为 RULE_ID：
-- 1. FRTB SBA 汇总结果移除 TREE_ID。
-- 2. FRTB SBA 欧拉分解明细移除 TREE_ID。
-- 3. RRAO 结果使用 RULE_ID。

CREATE TABLE IF NOT EXISTS TB_OUT_FRTB_SBA_CLASS_RESULT_RULE_ID_20260623 (
    BATCH_ID                        VARCHAR(64),
    DATA_DATE                       VARCHAR(16),
    RULE_ID                         VARCHAR(128),
    GROUP_TYPE                      VARCHAR(64),
    GROUP_VALUE                     VARCHAR(512),
    RISK_FACTOR_CLASS               VARCHAR(64),
    CAPITAL_TYPE                    VARCHAR(32),
    MAX_SIGN                        VARCHAR(16),
    RISK_CHARGE                     DECIMAL(38,10),
    NORMAL_DELTA                    DECIMAL(38,10),
    HIGH_DELTA                      DECIMAL(38,10),
    LOW_DELTA                       DECIMAL(38,10),
    NORMAL_VEGA                     DECIMAL(38,10),
    HIGH_VEGA                       DECIMAL(38,10),
    LOW_VEGA                        DECIMAL(38,10),
    NORMAL_CURVATURE                DECIMAL(38,10),
    HIGH_CURVATURE                  DECIMAL(38,10),
    LOW_CURVATURE                   DECIMAL(38,10),
    CREATED_AT                      VARCHAR(32),
    UPDATED_AT                      VARCHAR(32)
)
UNIQUE KEY(BATCH_ID, DATA_DATE, RULE_ID, GROUP_TYPE, GROUP_VALUE, RISK_FACTOR_CLASS, CAPITAL_TYPE)
DISTRIBUTED BY HASH(BATCH_ID) BUCKETS 8
PROPERTIES (
    'replication_allocation' = 'tag.location.default: 1',
    'enable_unique_key_merge_on_write' = 'true'
);

INSERT INTO TB_OUT_FRTB_SBA_CLASS_RESULT_RULE_ID_20260623 (
    BATCH_ID, DATA_DATE, RULE_ID, GROUP_TYPE, GROUP_VALUE, RISK_FACTOR_CLASS, CAPITAL_TYPE, MAX_SIGN,
    RISK_CHARGE, NORMAL_DELTA, HIGH_DELTA, LOW_DELTA, NORMAL_VEGA, HIGH_VEGA, LOW_VEGA,
    NORMAL_CURVATURE, HIGH_CURVATURE, LOW_CURVATURE, CREATED_AT, UPDATED_AT
)
SELECT
    BATCH_ID, DATA_DATE, RULE_ID, GROUP_TYPE, GROUP_VALUE, RISK_FACTOR_CLASS, CAPITAL_TYPE, MAX_SIGN,
    RISK_CHARGE, NORMAL_DELTA, HIGH_DELTA, LOW_DELTA, NORMAL_VEGA, HIGH_VEGA, LOW_VEGA,
    NORMAL_CURVATURE, HIGH_CURVATURE, LOW_CURVATURE, CREATED_AT, UPDATED_AT
FROM TB_OUT_FRTB_SBA_CLASS_RESULT;

ALTER TABLE TB_OUT_FRTB_SBA_CLASS_RESULT RENAME TB_OUT_FRTB_SBA_CLASS_RESULT_TREE_ID_BAK_20260623;
ALTER TABLE TB_OUT_FRTB_SBA_CLASS_RESULT_RULE_ID_20260623 RENAME TB_OUT_FRTB_SBA_CLASS_RESULT;

CREATE TABLE IF NOT EXISTS TB_OUT_FRTB_SBA_DECOMP_DETAIL_RULE_ID_20260623 (
    BATCH_ID                        VARCHAR(64),
    DATA_DATE                       VARCHAR(16),
    RULE_ID                         VARCHAR(128),
    GROUP_TYPE                      VARCHAR(64),
    GROUP_VALUE                     VARCHAR(512),
    RISK_FACTOR_CLASS               VARCHAR(64),
    RISK_FACTOR_BUCKET              VARCHAR(64),
    RISK_FACTOR_ID                  VARCHAR(256),
    RISK_FACTOR_VERTEX_1            VARCHAR(128),
    RISK_FACTOR_VERTEX_2            VARCHAR(128),
    RISK_FACTOR_TYPE                VARCHAR(64),
    SENSITIVITY_TYPE                VARCHAR(64),
    UNIT_CONTRIBUTION               DECIMAL(38,10),
    CREATED_AT                      VARCHAR(32),
    UPDATED_AT                      VARCHAR(32)
)
UNIQUE KEY(BATCH_ID, DATA_DATE, RULE_ID, GROUP_TYPE, GROUP_VALUE,
           RISK_FACTOR_CLASS, RISK_FACTOR_BUCKET, RISK_FACTOR_ID,
           RISK_FACTOR_VERTEX_1, RISK_FACTOR_VERTEX_2, RISK_FACTOR_TYPE, SENSITIVITY_TYPE)
DISTRIBUTED BY HASH(BATCH_ID) BUCKETS 8
PROPERTIES (
    'replication_allocation' = 'tag.location.default: 1',
    'enable_unique_key_merge_on_write' = 'true'
);

INSERT INTO TB_OUT_FRTB_SBA_DECOMP_DETAIL_RULE_ID_20260623 (
    BATCH_ID, DATA_DATE, RULE_ID, GROUP_TYPE, GROUP_VALUE, RISK_FACTOR_CLASS, RISK_FACTOR_BUCKET,
    RISK_FACTOR_ID, RISK_FACTOR_VERTEX_1, RISK_FACTOR_VERTEX_2, RISK_FACTOR_TYPE, SENSITIVITY_TYPE,
    UNIT_CONTRIBUTION, CREATED_AT, UPDATED_AT
)
SELECT
    BATCH_ID, DATA_DATE, RULE_ID, GROUP_TYPE, GROUP_VALUE, RISK_FACTOR_CLASS, RISK_FACTOR_BUCKET,
    RISK_FACTOR_ID, RISK_FACTOR_VERTEX_1, RISK_FACTOR_VERTEX_2, RISK_FACTOR_TYPE, SENSITIVITY_TYPE,
    UNIT_CONTRIBUTION, CREATED_AT, UPDATED_AT
FROM TB_OUT_FRTB_SBA_DECOMP_DETAIL;

ALTER TABLE TB_OUT_FRTB_SBA_DECOMP_DETAIL RENAME TB_OUT_FRTB_SBA_DECOMP_DETAIL_TREE_ID_BAK_20260623;
ALTER TABLE TB_OUT_FRTB_SBA_DECOMP_DETAIL_RULE_ID_20260623 RENAME TB_OUT_FRTB_SBA_DECOMP_DETAIL;

CREATE TABLE IF NOT EXISTS TB_OUT_TRADE_RRAO_RESULT_RULE_ID_20260623 (
    BATCH_ID            VARCHAR(64),
    DATA_DATE           VARCHAR(16),
    RULE_ID             VARCHAR(128),
    GROUP_TYPE          VARCHAR(64),
    GROUP_VALUE         VARCHAR(512),
    RRAO_TYPE           VARCHAR(64),
    TRADE_COUNT         BIGINT,
    RRAO_NOTIONAL       DECIMAL(38,10),
    RRAO_CAPITAL        DECIMAL(38,10),
    CREATED_AT          VARCHAR(32)
)
UNIQUE KEY(BATCH_ID, DATA_DATE, RULE_ID, GROUP_TYPE, GROUP_VALUE, RRAO_TYPE)
DISTRIBUTED BY HASH(BATCH_ID) BUCKETS 8
PROPERTIES (
    'replication_allocation' = 'tag.location.default: 1',
    'enable_unique_key_merge_on_write' = 'true'
);

INSERT INTO TB_OUT_TRADE_RRAO_RESULT_RULE_ID_20260623 (
    BATCH_ID, DATA_DATE, RULE_ID, GROUP_TYPE, GROUP_VALUE, RRAO_TYPE,
    TRADE_COUNT, RRAO_NOTIONAL, RRAO_CAPITAL, CREATED_AT
)
SELECT
    BATCH_ID, DATA_DATE, TREE_ID, GROUP_TYPE, GROUP_VALUE, RRAO_TYPE,
    TRADE_COUNT, RRAO_NOTIONAL, RRAO_CAPITAL, CREATED_AT
FROM TB_OUT_TRADE_RRAO_RESULT;

ALTER TABLE TB_OUT_TRADE_RRAO_RESULT RENAME TB_OUT_TRADE_RRAO_RESULT_TREE_ID_BAK_20260623;
ALTER TABLE TB_OUT_TRADE_RRAO_RESULT_RULE_ID_20260623 RENAME TB_OUT_TRADE_RRAO_RESULT;

