-- =====================================================================
-- H2 输出表 DDL
-- 情景文件结果表：存储每次 batch 批量估值的情景文件（scenario_set）数据。
-- 字段参考 TB_17_SCENARIO_RESULT_TMP，增加 BATCH_ID/JOB_ID 等追踪字段。
-- =====================================================================

CREATE TABLE IF NOT EXISTS TB_OUT_SCENARIO_FILE_DETAIL (
    ID                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    REQUEST_ID          VARCHAR(128),
    JOB_ID              VARCHAR(64),
    BATCH_ID            VARCHAR(64),
    SEQ_NO              BIGINT,
    DATA_DATE           VARCHAR(16),
    OP_CODE             VARCHAR(64),
    SCENARIO_ID         VARCHAR(128),
    SUBSCENARIO_ID      VARCHAR(128),
    SCENARIO_NAME       VARCHAR(256),
    SCENARIO_TYPE       VARCHAR(64),
    RISKFACTOR_TYPE     VARCHAR(64),
    RISKFACTOR_ID       VARCHAR(256),
    RISKFACTOR_VERTEX1  VARCHAR(128),
    RISKFACTOR_VERTEX2  VARCHAR(128),
    CHANGE_VALUE        DECIMAL(20, 8),
    RISKFACTOR_TERM     VARCHAR(64),
    ORI_VALUE           DECIMAL(20, 8),
    SCENARIO_RESULT     DECIMAL(20, 8),
    MODIFIER            VARCHAR(128),
    CREATED_AT          BIGINT,
    UPDATED_AT          BIGINT
);

CREATE INDEX IF NOT EXISTS idx_scenario_file_batch
    ON TB_OUT_SCENARIO_FILE_DETAIL (BATCH_ID);

CREATE INDEX IF NOT EXISTS idx_scenario_file_scenario
    ON TB_OUT_SCENARIO_FILE_DETAIL (SCENARIO_ID);

CREATE INDEX IF NOT EXISTS idx_scenario_file_date
    ON TB_OUT_SCENARIO_FILE_DETAIL (DATA_DATE);

CREATE INDEX IF NOT EXISTS idx_scenario_file_job
    ON TB_OUT_SCENARIO_FILE_DETAIL (JOB_ID);

-- =====================================================================
-- 情景 PnL 分解结果表
-- 一个原始 decomp 场景对应一条 scenario_result，trade_data 中携带五组风险类结果。
-- =====================================================================

CREATE TABLE IF NOT EXISTS TB_OUT_TRADE_SCENARIO_DECOMP_DETAIL (
    ID                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    REQUEST_ID          VARCHAR(128),
    JOB_ID              VARCHAR(64),
    BATCH_ID            VARCHAR(64),
    SEQ_NO              BIGINT,
    DATA_DATE           VARCHAR(16),
    OP_CODE             VARCHAR(64),
    SCENARIO_ID         VARCHAR(128),
    SUBSCENARIO_ID      VARCHAR(128),
    SCENARIO_NAME       VARCHAR(256),
    INSTRUMENT_ID       VARCHAR(128),
    PRODUCT_CODE        VARCHAR(64),
    BASE_VALUATION_CNY  DECIMAL(20, 8),
    IR_VALUATION        DECIMAL(20, 8),
    IR_PNL              DECIMAL(20, 8),
    FX_VALUATION        DECIMAL(20, 8),
    FX_PNL              DECIMAL(20, 8),
    EQ_VALUATION        DECIMAL(20, 8),
    EQ_PNL              DECIMAL(20, 8),
    COMM_VALUATION      DECIMAL(20, 8),
    COMM_PNL            DECIMAL(20, 8),
    ALL_VALUATION       DECIMAL(20, 8),
    ALL_PNL             DECIMAL(20, 8),
    RESULT_JSON         CLOB,
    CREATED_AT          BIGINT,
    UPDATED_AT          BIGINT
);

CREATE INDEX IF NOT EXISTS idx_scenario_decomp_batch
    ON TB_OUT_TRADE_SCENARIO_DECOMP_DETAIL (BATCH_ID);

CREATE INDEX IF NOT EXISTS idx_scenario_decomp_scenario
    ON TB_OUT_TRADE_SCENARIO_DECOMP_DETAIL (SCENARIO_ID);

CREATE INDEX IF NOT EXISTS idx_scenario_decomp_job
    ON TB_OUT_TRADE_SCENARIO_DECOMP_DETAIL (JOB_ID);

-- =====================================================================
-- 基准估值结果表
-- =====================================================================

CREATE TABLE IF NOT EXISTS TB_OUT_TRADE_RESULT_DETAIL (
    ID              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    REQUEST_ID      VARCHAR(128),
    JOB_ID          VARCHAR(64),
    BATCH_ID        VARCHAR(64),
    SEQ_NO          BIGINT,
    DATA_DATE       VARCHAR(16),
    OP_CODE         VARCHAR(64),
    INSTRUMENT_ID   VARCHAR(128),
    PRODUCT_CODE    VARCHAR(64),
    PORTFOLIO       VARCHAR(128),
    DESK            VARCHAR(64),
    TRADER          VARCHAR(64),
    POSITION        DECIMAL(20, 8),
    VALUATION_UNIT  DECIMAL(20, 8),
    VALUATION       DECIMAL(20, 8),
    VALUATION_CCY   VARCHAR(8),
    VALUATION_CNY   DECIMAL(20, 8),
    PV01            DECIMAL(20, 8),
    DELTA           DECIMAL(20, 8),
    GAMMA           DECIMAL(20, 8),
    VEGA            DECIMAL(20, 8),
    THETA           DECIMAL(20, 8),
    RHO             DECIMAL(20, 8),
    STATUS          VARCHAR(16),
    ERROR           CLOB,
    DETAIL          CLOB,
    ERRORS_JSON     CLOB,
    CASHFLOW_JSON   CLOB,
    RESULT_JSON     CLOB,
    CREATED_AT      BIGINT,
    UPDATED_AT      BIGINT
);

CREATE INDEX IF NOT EXISTS idx_result_detail_batch
    ON TB_OUT_TRADE_RESULT_DETAIL (BATCH_ID);

CREATE INDEX IF NOT EXISTS idx_result_detail_job
    ON TB_OUT_TRADE_RESULT_DETAIL (JOB_ID);

-- =====================================================================
-- 情景 PnL 结果表
-- =====================================================================

CREATE TABLE IF NOT EXISTS TB_OUT_TRADE_SCENARIO_RESULT_DETAIL (
    ID                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    REQUEST_ID              VARCHAR(128),
    JOB_ID                  VARCHAR(64),
    BATCH_ID                VARCHAR(64),
    SEQ_NO                  BIGINT,
    DATA_DATE               VARCHAR(16),
    OP_CODE                 VARCHAR(64),
    SCENARIO_ID             VARCHAR(128),
    SUBSCENARIO_ID          VARCHAR(128),
    SCENARIO_NAME           VARCHAR(256),
    INSTRUMENT_ID           VARCHAR(128),
    PRODUCT_CODE            VARCHAR(64),
    BASE_VALUATION_CNY      DECIMAL(20, 8),
    SCENARIO_VALUATION_CNY  DECIMAL(20, 8),
    PNL                     DECIMAL(20, 8),
    ERROR                   CLOB,
    DETAIL                  CLOB,
    RESULT_JSON             CLOB,
    CREATED_AT              BIGINT,
    UPDATED_AT              BIGINT
);

CREATE INDEX IF NOT EXISTS idx_scenario_result_batch
    ON TB_OUT_TRADE_SCENARIO_RESULT_DETAIL (BATCH_ID);

-- =====================================================================
-- FRTB 敏感性明细表
-- =====================================================================

CREATE TABLE IF NOT EXISTS TB_OUT_TRADE_FRTB_SENSITIVITY_DETAIL (
    ID                              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    REQUEST_ID                      VARCHAR(128),
    JOB_ID                          VARCHAR(64),
    BATCH_ID                        VARCHAR(64),
    SEQ_NO                          BIGINT,
    DATA_DATE                       VARCHAR(16),
    OP_CODE                         VARCHAR(64),
    INSTRUMENT_ID                   VARCHAR(128),
    PRODUCT_CODE                    VARCHAR(64),
    RISK_FACTOR_ID                  VARCHAR(256),
    RISK_FACTOR_VERTEX_1            VARCHAR(128),
    RISK_FACTOR_VERTEX_2            VARCHAR(128),
    RISK_FACTOR_CLASS               VARCHAR(64),
    RISK_FACTOR_BUCKET              VARCHAR(64),
    RISK_FACTOR_TYPE                VARCHAR(64),
    SENSITIVITY_TYPE                VARCHAR(64),
    SENSITIVITY_VAL_INST_CURR       DECIMAL(20, 8),
    INSTRUMENT_CURRENCY             VARCHAR(8),
    SENSITIVITY_VAL_INST_CURR_CNY   DECIMAL(20, 8),
    DETAIL_JSON                     CLOB,
    CREATED_AT                      BIGINT,
    UPDATED_AT                      BIGINT
);

CREATE INDEX IF NOT EXISTS idx_frtb_sens_batch
    ON TB_OUT_TRADE_FRTB_SENSITIVITY_DETAIL (BATCH_ID);

CREATE INDEX IF NOT EXISTS idx_frtb_sens_job
    ON TB_OUT_TRADE_FRTB_SENSITIVITY_DETAIL (JOB_ID);

-- =====================================================================
-- DRC 违约风险明细表
-- =====================================================================

CREATE TABLE IF NOT EXISTS TB_OUT_TRADE_DRC_DETAIL (
    ID                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    REQUEST_ID          VARCHAR(128),
    JOB_ID              VARCHAR(64),
    BATCH_ID            VARCHAR(64),
    SEQ_NO              BIGINT,
    DATA_DATE           VARCHAR(16),
    OP_CODE             VARCHAR(64),
    INSTRUMENT_ID       VARCHAR(128),
    PRODUCT_CODE        VARCHAR(64),
    PORTFOLIO_CODE      VARCHAR(128),
    SECURITY_ID         VARCHAR(128),
    SECURITY_TYPE       VARCHAR(64),
    LEGAL_ENTITY        VARCHAR(128),
    DRC_BUCKET          VARCHAR(64),
    JTD_TYPE            VARCHAR(64),
    SENIORITY           INT,
    TERM_TO_MATURITY    DECIMAL(20, 8),
    MODIFIED_REMAIN_TERM DECIMAL(20, 8),
    RISK_WEIGHT         DECIMAL(20, 8),
    JTD                 DECIMAL(20, 8),
    JTD_CNY             DECIMAL(20, 8),
    INSTRUMENT_VALUE    DECIMAL(20, 8),
    FRTB_LGD            DECIMAL(20, 8),
    NOTIONAL            DECIMAL(20, 8),
    DETAIL_JSON         CLOB,
    CREATED_AT          BIGINT,
    UPDATED_AT          BIGINT
);

CREATE INDEX IF NOT EXISTS idx_drc_batch
    ON TB_OUT_TRADE_DRC_DETAIL (BATCH_ID);
