-- Doris 不允许把现有可空键列直接修改为非空，也不支持 VARCHAR 直接修改为 DATETIME(3)。
-- 存量表迁移必须基于 SHOW CREATE TABLE 重建同结构临时表，通过 INSERT SELECT 完成类型转换，
-- 核对行数后交换表名。新建环境直接执行 mr_output_schema_doris.sql。
-- 本文件用于迁移后结构复核，避免误执行不完整的原位 ALTER。

SELECT COLUMN_TYPE, IS_NULLABLE, COUNT(*) AS COLUMN_COUNT
FROM information_schema.COLUMNS
WHERE TABLE_SCHEMA = 'engine_result_db'
  AND TABLE_NAME LIKE 'TB_%'
  AND TABLE_NAME NOT LIKE '%BAK%'
  AND TABLE_NAME <> 'TB_OUT_IMA_ES_RESULT_DETAIL'
  AND COLUMN_NAME = 'DATA_DATE'
GROUP BY COLUMN_TYPE, IS_NULLABLE;

SELECT COLUMN_NAME, COLUMN_TYPE, COUNT(*) AS COLUMN_COUNT
FROM information_schema.COLUMNS
WHERE TABLE_SCHEMA = 'engine_result_db'
  AND TABLE_NAME LIKE 'TB_%'
  AND TABLE_NAME NOT LIKE '%BAK%'
  AND TABLE_NAME <> 'TB_OUT_IMA_ES_RESULT_DETAIL'
  AND COLUMN_NAME IN (
      'START_DATE', 'END_DATE', 'EXCEPTION_DATE',
      'CREATED_AT', 'UPDATED_AT', 'CREATE_TIME'
  )
GROUP BY COLUMN_NAME, COLUMN_TYPE
ORDER BY COLUMN_NAME, COLUMN_TYPE;
