-- DRC 汇总结果表 CAPITAL_TYPE 口径迁移脚本
--
-- 适用场景：
-- 已存在 TB_OUT_TRADE_DRC_RESULT.DECOMP_FLAG 旧字段，需要统一为 CAPITAL_TYPE。
--
-- 说明：
-- Doris UNIQUE KEY 变更采用重命名旧表、创建新表、迁移旧数据的方式。

ALTER TABLE TB_OUT_TRADE_DRC_RESULT RENAME TB_OUT_TRADE_DRC_RESULT_BAK_20260522_CAPITAL_TYPE;

CREATE TABLE TB_OUT_TRADE_DRC_RESULT (
    BATCH_ID            VARCHAR(64),
    DATA_DATE           VARCHAR(16),
    RULE_ID             VARCHAR(128),
    GROUP_TYPE          VARCHAR(64),
    GROUP_VALUE         VARCHAR(512),
    CAPITAL_TYPE        VARCHAR(32),
    AGG_LEVEL           VARCHAR(32),
    DRC_TYPE            VARCHAR(64),
    DRC_BUCKET          VARCHAR(64),
    LEGAL_ENTITY        VARCHAR(128),
    REQUEST_ID          VARCHAR(128),
    JOB_ID              VARCHAR(64),
    DRC_VALUE           DECIMAL(38, 10),
    CREATED_AT          VARCHAR(32)
)
UNIQUE KEY(BATCH_ID, DATA_DATE, RULE_ID, GROUP_TYPE, GROUP_VALUE, CAPITAL_TYPE, AGG_LEVEL, DRC_TYPE, DRC_BUCKET, LEGAL_ENTITY)
DISTRIBUTED BY HASH(BATCH_ID) BUCKETS 8
PROPERTIES (
    "replication_allocation" = "tag.location.default: 1",
    "enable_unique_key_merge_on_write" = "true"
);

INSERT INTO TB_OUT_TRADE_DRC_RESULT (
    BATCH_ID,
    DATA_DATE,
    RULE_ID,
    GROUP_TYPE,
    GROUP_VALUE,
    CAPITAL_TYPE,
    AGG_LEVEL,
    DRC_TYPE,
    DRC_BUCKET,
    LEGAL_ENTITY,
    REQUEST_ID,
    JOB_ID,
    DRC_VALUE,
    CREATED_AT
)
SELECT
    BATCH_ID,
    DATA_DATE,
    RULE_ID,
    GROUP_TYPE,
    GROUP_VALUE,
    CASE
        WHEN DECOMP_FLAG = 'DRC_VALUE' THEN 'NONADDITIVE'
        WHEN DECOMP_FLAG = 'DECOMP_LEGALENTITY' THEN 'ADDITIVE'
        ELSE DECOMP_FLAG
    END,
    AGG_LEVEL,
    DRC_TYPE,
    DRC_BUCKET,
    LEGAL_ENTITY,
    REQUEST_ID,
    JOB_ID,
    DRC_VALUE,
    CREATED_AT
FROM TB_OUT_TRADE_DRC_RESULT_BAK_20260522_CAPITAL_TYPE;
