-- BA-CVA结果表迁移
CREATE TABLE IF NOT EXISTS TB_OUT_CVA_RESULT (
    ID BIGINT NOT NULL AUTO_INCREMENT,
    BATCH_ID VARCHAR(64), DATA_DATE DATE NOT NULL, CALCULATION_MODE VARCHAR(16), REDUCTION_REASON VARCHAR(32),
    DERIVATIVE_NOTIONAL_CNY DECIMAL(38,10),
    COUNTERPARTY_COUNT INT, NETTING_SET_COUNT INT, HEDGE_COUNT INT,
    K_REDUCED DECIMAL(38,10), K_HEDGED DECIMAL(38,10), K_FULL DECIMAL(38,10),
    CVA_CAPITAL_REQUIREMENT DECIMAL(38,10), CVA_RWA DECIMAL(38,10), CREATE_TIME DATETIME(3)
)
UNIQUE KEY(ID) DISTRIBUTED BY HASH(ID) BUCKETS 4
PROPERTIES ("replication_allocation" = "tag.location.default: 1", "enable_unique_key_merge_on_write" = "true");

CREATE TABLE IF NOT EXISTS TB_OUT_CVA_COUNTERPARTY_DETAIL (
    ID BIGINT NOT NULL AUTO_INCREMENT,
    BATCH_ID VARCHAR(64), DATA_DATE DATE NOT NULL, COUNTERPARTY_ID VARCHAR(128),
    SCVA DECIMAL(38,10), SINGLE_NAME_HEDGE DECIMAL(38,10), HEDGING_MISALIGNMENT DECIMAL(38,10),
    CREATE_TIME DATETIME(3)
)
UNIQUE KEY(ID) DISTRIBUTED BY HASH(ID) BUCKETS 8
PROPERTIES ("replication_allocation" = "tag.location.default: 1", "enable_unique_key_merge_on_write" = "true");

CREATE TABLE IF NOT EXISTS TB_OUT_CVA_NETTING_SET_DETAIL (
    ID BIGINT NOT NULL AUTO_INCREMENT,
    BATCH_ID VARCHAR(64), DATA_DATE DATE NOT NULL, NETTING_SET_ID VARCHAR(128), COUNTERPARTY_ID VARCHAR(128),
    EFFECTIVE_MATURITY_YEARS DECIMAL(38,10), EAD DECIMAL(38,10), RISK_WEIGHT DECIMAL(18,10),
    DISCOUNT_FACTOR DECIMAL(38,10), SCVA_CONTRIBUTION DECIMAL(38,10), CREATE_TIME DATETIME(3)
)
UNIQUE KEY(ID) DISTRIBUTED BY HASH(ID) BUCKETS 8
PROPERTIES ("replication_allocation" = "tag.location.default: 1", "enable_unique_key_merge_on_write" = "true");

CREATE TABLE IF NOT EXISTS TB_OUT_CVA_HEDGE_DETAIL (
    ID BIGINT NOT NULL AUTO_INCREMENT,
    BATCH_ID VARCHAR(64), DATA_DATE DATE NOT NULL, HEDGE_ID VARCHAR(128), HEDGE_TYPE VARCHAR(32),
    COUNTERPARTY_ID VARCHAR(128), RISK_WEIGHT DECIMAL(18,10), CORRELATION DECIMAL(18,10),
    REMAINING_MATURITY_YEARS DECIMAL(38,10), NOTIONAL_CNY DECIMAL(38,10), DISCOUNT_FACTOR DECIMAL(38,10),
    SINGLE_NAME_HEDGE DECIMAL(38,10), INDEX_HEDGE DECIMAL(38,10), HEDGING_MISALIGNMENT DECIMAL(38,10),
    CREATE_TIME DATETIME(3)
)
UNIQUE KEY(ID) DISTRIBUTED BY HASH(ID) BUCKETS 8
PROPERTIES ("replication_allocation" = "tag.location.default: 1", "enable_unique_key_merge_on_write" = "true");
